socialApp/socialApp/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from social import views as social_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('social/', social_views.sendMessage,name='send_message'),
    path('demo/',social_views.demo),
    path('send/',social_views.send,name='send'),
    path('agente/',social_views.viewMessage,name='view_message'), 
    path('messages/',social_views.displayMessage,name='display_message'),
    path('hooks',social_views.hooks,name='hooks'),
    path('contact/',social_views.showContact,name='show_contact'),
    path('conversations/',social_views.listConversations,name='list_conversations'),
    path('conversation/messages/',social_views.displayMessages4Conversation, name="display_messages"),
    path('supervisor/',social_views.viewDashboard,name="view_dashboard"),
    
  
    path('agente/login/', social_views.login_view, name='login'),
   
    
]

socialApp/social/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

#Custom imports
import urllib.request as urllib2
import urllib
import json
import time

class Whabox(models.Model):
	event=models.CharField(max_length=255,null=True)
	token=models.CharField(max_length=255,null=True)
	contact_uid=models.CharField(max_length=255,null=True)
	contact_name=models.CharField(max_length=255,null=True)
	contact_type=models.CharField(max_length=255,null=True)
	message_dtm=models.CharField(max_length=255,null=True)
	message_uid=models.CharField(max_length=255,null=True)
	message_cuid=models.CharField(max_length=255,null=True)
	message_dir=models.CharField(max_length=255,null=True)
	message_type=models.CharField(max_length=255,null=True)
	message_text=models.CharField(max_length=255,null=True)
	message_ack=models.CharField(max_length=255,null=True)
	
	def __str__(self):
		return self.event+" "+self.token+" "+self.contact_uid+" "+self.contact_name+" "+self.contact_type+" "+self.contact_name+" "+self.message_dtm+" "+self.message_uid+" "+self.message_cuid+" "+self.message_dir+" "+self.message_type+" "+self.message_text+" "+self.message_ack

class Tipo(models.Model):
	title=models.CharField(max_length=50)
	description=models.CharField(max_length=255)
	user=models.ForeignKey(User,on_delete=models.CASCADE)
	created=models.DateTimeField(auto_now_add=True)
	modified=models.DateTimeField(auto_now=True)
	
class Conversation(models.Model):
	STATUS = (
    	(1, ("open")),
    	(2, ("process")),
    	(3, ("close"))
	)
	RED = (
    	(1, ("TW")),
    	(2, ("WA")),
    	(3, ("FB")),
	(4, ("IG"))
	)
	
	message_cuid=models.CharField(max_length=255)
	contact_uid=models.CharField(max_length=255)
	created=models.DateTimeField(auto_now_add=True)
	modified=models.DateTimeField(auto_now=True)
	user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
	estado= models.IntegerField(choices=STATUS)
	red=models.IntegerField(choices=RED)
	tipo=models.ForeignKey(Tipo,on_delete=models.CASCADE,null=True)
	
	def __str__(self):
		return self.message_cuid+" "+self.contact_uid

	
class Message(models.Model):
	STATUS = (
    	(0, ("NOT SEND")),
    	(1, ("SEND")),
    	(2, ("DELIVERED")),
	(3, ("READ")),
	)
	DIR = (
    	(1, ("I")),
    	(2, ("O"))
	)
	conversation=models.ForeignKey(Conversation,on_delete=models.CASCADE)
	message_text=models.CharField(max_length=255)
	direction= models.IntegerField(choices=DIR)
	estado=models.IntegerField(choices=STATUS)
	created=models.DateTimeField(auto_now_add=True)
	user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
	
class WhaboxSender:
  def __init__(self, token, uid, url, custom_uid):
    self.token = token
    self.uid = uid
    self.url = url
    self.custom_uid = custom_uid
          
  def sendMessage(self, message, to):	
    data = urllib.parse.urlencode({"token":self.token,"uid":self.uid,"to":to,"custom_uid":self.custom_uid,"text":message}).encode('utf-8') 
    req = urllib2.Request(self.url,data)
    response = urllib2.urlopen(req)
    result = response.read().decode('utf-8')
    #Obtener el resultado JSON
    obj=json.loads(result)
    message=obj['success']
    return message
                	
class Agente(models.Model):
	STATUS = (
    (1, ("En linea")),
    (2, ("Ocupado")),
    (3, ("Receso")),
    (4, ("Baño"))
	)
	user=models.OneToOneField(User, on_delete=models.CASCADE)
	created=models.DateTimeField(auto_now_add=True)
	modified=models.DateTimeField(auto_now=True)
	estado= models.IntegerField(choices=STATUS)
	
	def __str__(self):
		return self.user.username
	
	
	
	
	

	

socialApp/social/forms.py
from django import forms
from social.models import Whabox


class WhatForm(forms.Form):
	cid=forms.CharField(max_length=100)
	destino=forms.CharField(max_length=100)
	text=forms.CharField(max_length=100)
	
	

socialApp/social/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import authenticate, login, logout

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from datetime import datetime
import urllib.request as urllib2
import urllib
import time


#Custom imports
from social.forms import WhatForm
from social.models import Whabox, Conversation, Message, WhaboxSender,Agente


#JSON LIBRARY
import json

# Create your views here.

def demo(request):
  return render(request,'social/demo.html',{})  


def send(request):
  token='d42dbfc3434f650ed58b33e4955fa9cc5be1dd2f26439'
  uid='595974108801'
  url='https://www.waboxapp.com/api/send/chat'
  custom_uid= get_random_string(length=32)
  if request.method=='POST':
    form=WhatForm(request.POST)
    if form.is_valid():
      destino=form.cleaned_data.get("destino")
      text=form.cleaned_data.get("text")
      wbs= WhaboxSender(token,uid,url,custom_uid)
      result=wbs.sendMessage(text,destino)
      return render (request,'social/messajes.html',{})
  else:
    form=WhatForm()
  return render (request,'social/send.html',{})  
  
def sendMessage(request):
  token='d42dbfc3434f650ed58b33e4955fa9cc5be1dd2f26439'
  uid='595974108801'
  url='https://www.waboxapp.com/api/send/chat'
  custom_uid= get_random_string(length=32)
  if request.method=='POST':
    form=WhatForm(request.POST)
    if form.is_valid():
      destino=form.cleaned_data.get("destino")
      text=form.cleaned_data.get("text")
      cid=form.cleaned_data.get("cid")
      wbs= WhaboxSender(token,uid,url,custom_uid)
      result=wbs.sendMessage(text,destino)
      conversation=Conversation.objects.get(pk=cid)
      return render (request,'social/messajes.html',{'conversation':conversation})
  else:
    form=WhatForm()
  return render (request,'social/messajes.html',{'conversation':conversation})

def sendMessage2(request):
  token='d42dbfc3434f650ed58b33e4955fa9cc5be1dd2f26439'
  uid='595974108801'
  url='https://www.waboxapp.com/api/send/chat'
  custom_uid= get_random_string(length=32)
  if request.method=='POST':
    form=WhatForm(request.POST)
    if form.is_valid():
      destino=form.cleaned_data.get("destino")
      text=form.cleaned_data.get("text")
      cid=form.cleaned_data.get("cid")
      wbs= WhaboxSender(token,uid,url,custom_uid)
      result=wbs.sendMessage(text,destino)
      conversation=Conversation.objects.get(pk=cid)
      return render (request,'social/messajes.html')
  else:
    form=WhatForm()
  return render (request,'social/messajes.html')


def hooks(request):
  if request.method=='POST':
    whabox= Whabox()
    whabox.event=request.POST.get("event")
    whabox.token=request.POST.get("token")
    whabox.contact_uid=request.POST.get("contact[uid]")
    whabox.contact_name=request.POST.get("contact[name]")
    whabox.contact_type=request.POST.get("contact[type]")
    whabox.message_dtm=request.POST.get("message[dtm]")
    whabox.message_uid=request.POST.get("message[uid]")
    whabox.message_cuid=request.POST.get("message[cuid]")
    whabox.message_dir=request.POST.get("message[dir]")
    whabox.message_type=request.POST.get("message[type]")
    whabox.message_text=request.POST.get("message[body][text]")
    whabox.message_ack=request.POST.get("message[ack]")
    #whabox.save()
    
    conversations= Conversation.objects.filter(contact_uid=whabox.contact_uid)
    if conversations:
      conversation=conversations.first()
    else:
      #Crear nueva conversacion y adjuntar el mensaje
      conversation=Conversation()
      conversation.contact_uid=whabox.contact_uid
      conversation.message_cuid=get_random_string(length=32)
           
      #Accionar a la nueva conversacion
      token='d42dbfc3434f650ed58b33e4955fa9cc5be1dd2f26439'
      uid='595974108801'
      url='https://www.waboxapp.com/api/send/chat'
      custom_uid= get_random_string(length=15)   
      wbs= WhaboxSender(token,uid,url,custom_uid)
      text="Usted se ha comunicado a Pytyvo. En breve será atendido"
      result= wbs.sendMessage(text,conversation.contact_uid)
      
      if result:
        print("Se ha enviado correctmente el mensaje")
      else:
        print("No se ha podido enviar el mensaje")
    
    #Trabajar por el mensaje
    message=Message()
    message.conversation=conversation
    message.message_text=whabox.message_text
    message.estado=whabox.message_ack
    if whabox.message_dir=='i':
      message.direction=1
    else:
      message.direction=2
    conversation.estado=1
    conversation.red=2
    
    #Grabar
    conversation.save()
    message.save()
       
  
def viewMessage(request):
  conversations=None
  conversations=Conversation.objects.order_by('-modified')
  conversation=conversations.first()
  if request.method=='POST':
    conversation= Conversation.objects.get(contact_uid=request.POST.get('customer_uid'))
  return render (request,'social/mensajes.html',{'conversations':conversations,'conversation':conversation})       
  
def displayMessage(request):
  return render (request,'social/messajes.html',{}) 
  
def listConversations(request):
  conversations=Conversation.objects.order_by('-modified')
  return render (request,'social/contacts_content.html',{'conversations':conversations})

def showContact(request):
  if request.method=='POST':
    conversation_id=request.POST.get('conversation_id')
    conversation= Conversation.objects.get(pk=conversation_id)
    if conversation:
      conversation.estado=2
      conversation.save()
      print(conversation.contact_uid)
    return render (request,'social/contact_profile.html',{'conversation':conversation})  

def displayMessages4Conversation(request):
  conversation=Conversation.objects.get(pk=request.POST.get('conversation_id'))
  return render (request,'social/messajes.html',{'conversation':conversation})

def viewDashboard(request):
  conversations=Conversation.objects.filter(user__isnull=True)
  print("La cantidad de mensajes es: "+str(conversations.count()))
  return render (request, 'social/supervisor/dashboard.html',{'conversations':conversations})

def updateStatus(request):
  estado= request.POST.get('agent_status')
  id_agente= request.POST.get('agent_id')
  agente= Agente.objects.get('id_agente')
  agente.estado=estado
  agente.save()
  
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect('view_message')
        else:
            return render(request, 'social/agent/login.html', {'error': 'Usuario o password inválido'})
    return render(request, 'social/agent/login.html')
  
  
  
  
  
  
  
  
      
                  
              
    
  

socialApp/templates/social/contact_profile.html
      <img src="http://www.baytekgames.com/wp-content/uploads/2016/12/facebook-default-no-profile-pic1.jpg" alt="" />
      {%if conversation is not None%}
      <p>{{conversation.contact_uid}}</p>
      {%endif%}
      <div class="social-media">
        <i class="fa fa-facebook" aria-hidden="true"></i>
        <i class="fa fa-twitter" aria-hidden="true"></i>
        <i class="fa fa-instagram" aria-hidden="true"></i>
      </div>
     

socialApp/templates/social/contacts_content.html
{% load static %} 
<ul id="conversations"> 
        {%for conver in conversations%}
	 <li class="contact" id="conver.id">  
              <div class="wrap">
		  {%if conver.estado == 1%}
	       		<span class="contact-status busy" id="busy"></span>
          	  {%else%}
              		 <span class="contact-status online"></span> 
          	  {%endif%}    
                  <img src="{% static 'img/whatsapp.png' %}" alt="" />
                  <div class="meta">
                    <p class="name">{{conver.contact_uid}}</p>
                    <p class="preview">Disponible.</p>
                  </div>
             </div>
          </li>
        {%endfor%}
      </ul>

socialApp/templates/social/conversations.html
{% load static %}
<ul>
        {%for conver in conversations%}
          {%if conversation is not None%}
            {%if conver.contact_uid == conversation.contact_uid %}
              <li class="contact active" onclick="display_message({{conver.pk}})"> 
            {%else%}
              <li class="contact" onclick="display_message({{conver.pk}})">  
            {%endif%}
          {%else%}
            <li class="contact" onclick="display_message({{conver.pk}})">  
          {%endif%} 
              <div class="wrap">
              
                  <span class="contact-status online"></span>
                  <img src="{% static 'img/whatsapp.png' %}" alt="" />
                  <div class="meta">
                    <p class="name">{{conver.contact_uid}}</p>
                    <p class="preview">Disponible.</p>
                  </div>
               
             </div>
           
          </li>
        {%endfor%}
      </ul>

socialApp/templates/social/demo.html
<html>
   <head>
      <title>The jQuery Example</title>
      <script type = "text/javascript" 
         src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
      </script>
		
      <script type = "text/javascript" 
         src = "https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js">
      </script>
		
      <script type = "text/javascript" language = "javascript">
   
         $(document).ready(function() {            
               $(".target").effect( "highlight", {}, 3000 );
         });
			
      </script>
		
      <style>
         p {background-color:#bca; width:200px; border:1px solid green;}
         div{ width:100px; height:100px; background:red;}
      </style>
   </head>
	
   <body>
      <p>Click the button</p>
      <button id = "button"> Highlight </button>

      <div class = "target">
      </div>
   </body>
</html>

socialApp/templates/social/login.html
{% extends "base.html" %}
{%block head_content%}
{% load static %}
<title>Login - Agente</title>
{% endblock %}
{% block container %}    
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Favor inicie sesion</h3>
                    </div>
                    <div class="panel-body">
                        <form role="form">
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>
                                </div>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Password" name="password" type="password" value="">
                                </div>
                                <div class="checkbox">
                                    <label>
                                        <input name="remember" type="checkbox" value="Remember Me">Remember Me
                                    </label>
                                </div>
                                <!-- Change this to a button or input when using this as a form -->
                                <a href="index.html" class="btn btn-lg btn-success btn-block">Login</a>
                            </fieldset>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
  {% endblock %}

socialApp/templates/social/mensajes.html
{%extends "social/base.html"%}
{% load static %}
{%block head_content%}

<!-- Bootstrap core CSS-->
<link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
<!-- Custom fonts for this template-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/fontawesome-free/css/all.min.css' %}">
<!--script type = "text/javascript" src = "https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script-->
<!--script type = "text/javascript" src = "https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script-->

<!-- ESTO ES LO QUE DEBERIA DE FUNCIONAR -->

 <title>Panel de control - Agente</title>
      <script type = "text/javascript" src = "https://code.jquery.com/jquery-2.2.4.min.js"></script>
      <script type = "text/javascript" src = "https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>

<script type = "text/javascript" src = "{% static 'js/ajax.js'%}"></script>
<!--HASTA AQUI-->
{%endblock%}

{%block container%}
<div id="frame">
  <div id="sidepanel">
    <div id="profile">
      <div class="wrap">
        <img id="profile-img" src="http://www.baytekgames.com/wp-content/uploads/2016/12/facebook-default-no-profile-pic1.jpg" class="online" alt="" />
        <p>Derlis D&aacute;valos</p>
        <i class="fa fa-chevron-down expand-button" aria-hidden="true"></i>
        <div id="status-options">
          <ul>
            <li id="status-online" class="active"><span class="status-circle"></span> <p>Online</p></li>
            <li id="status-away"><span class="status-circle"></span> <p>Lejos</p></li>
            <li id="status-busy"><span class="status-circle"></span> <p>Ocupado</p></li>
            <li id="status-offline"><span class="status-circle"></span> <p>Fuera de Línea</p></li>
          </ul>
        </div>
        <div id="expanded">
          <label for="twitter"><i class="fa fa-facebook fa-fw" aria-hidden="true"></i></label>
          <input name="twitter" type="text" value="mikeross" />
          <label for="twitter"><i class="fa fa-twitter fa-fw" aria-hidden="true"></i></label>
          <input name="twitter" type="text" value="ross81" />
          <label for="twitter"><i class="fa fa-instagram fa-fw" aria-hidden="true"></i></label>
          <input name="twitter" type="text" value="mike.ross" />
        </div>
      </div>
    </div>
    <div id="search">
      <label for=""><i class="fa fa-search" aria-hidden="true"></i></label>
      <input type="text" placeholder="Buscar contactos..." />
    </div>
     <div id="contacts">
	  <div id="contacts_content">
	    <ul id="conversations"> 
		{%if conversations%}	    
        	{%for conver in conversations%}
	 	<li class="contact" id="{{conver.id}}" >  
              	<div class="wrap">
		  	{%if conver.estado == 1%}
	       			<span class="contact-status busy" id="busy"></span>
          	  	{%else%}
              		 	<span class="contact-status online"></span> 
          	  	{%endif%}    
                  	<img src="{% static 'img/whatsapp.png' %}" alt="" />
                  	<div class="meta">
                   	 <p class="name">{{conver.contact_uid}}</p>
                    	<p class="preview">Disponible.</p>
                  	</div>
             	</div>
          	</li>
        	{%endfor%}
	{%endif%}		    
      	</ul>	       
	</div> 
	<!--script>
	setInterval(updateConversations, 5000); //300000 MS == 5 minutes 
   	function updateConversations(){
      		$.ajax({
            		url:"/conversations/",  
            		success: function(response){
            		$("#contacts_content").html(response);    
            		},   
         	});
   	}    
	</script-->	         
    </div>
    <div id="bottom-bar">
      <button id="addcontact"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i> <span>Agregar contacto</span></button>
      <button id="settings"><i class="fa fa-cog fa-fw" aria-hidden="true"></i> <span>Configuraci&oacute;n</span></button>
    </div>
  </div>
  <div class="content"> 
     <div id="contact-profile" class="contact-profile">
	<img src="http://www.baytekgames.com/wp-content/uploads/2016/12/facebook-default-no-profile-pic1.jpg" alt="" />
      {%if conversation is not None%}
      <p>{{conversation.contact_uid}}</p>
      {%endif%}
      <div class="social-media">
        <i class="fa fa-facebook" aria-hidden="true"></i>
        <i class="fa fa-twitter" aria-hidden="true"></i>
        <i class="fa fa-instagram" aria-hidden="true"></i>
      </div>
	  </div>
	  
    <div id="messages" class="messages">
	<ul>
        {%for message in conversation.message_set.all %}
            	{%if message.direction == 1%}
                	<li class="replies">
            	{%else%}
                	<li class="sent">    
            	{%endif%}
                  	<p><strong>{{message.message_text}}</strong><span class="time_date">{{message.created|date:'d-m-y H:i'}}</span></p>
            	</li>
        {%endfor%}
      		
	</ul>  
   </div>
    <script>   
	setInterval(refresh_messages, 1000);    
	function refresh_messages(){    
	     var parametros = {
         	"conversation_id":{{conversation.pk}}
             };
	    $.ajax({
			url : "{%url 'display_messages'%}",
			type: "POST",
			data : parametros,
			success: function(response){ 
			$("#messages").html(response);
			},	
		});	
	}   
    </script>  
    <div class="message-input">
      <div class="wrap">
        <form method="POST" action="{%url 'send_message'%}" id="formConversation">
	<input type="hidden" name="cid" value="{{conversation.pk}}"/>
        <input type="hidden" name="destino" value="{{conversation.contact_uid}}"/>
	<input type="text" name="text" id="texto" placeholder="Escriba su mensaje..." autocomplete="off" />
        <i class="fa fa-paperclip attachment" aria-hidden="true"></i>
        <button class="submit" id="sendButton"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
        </form> 
	<script>
	$("#formConversation").submit(function(event){		
		event.preventDefault(); //prevent default action 
		
		var post_url = $(this).attr("action"); //get form action url
		var request_method = $(this).attr("method"); //get form GET/POST method
		var form_data = $(this).serialize(); //Encode form elements for submission
		$.ajax({
			url : post_url,
			type: request_method,
			data : form_data,
			beforeSend: function() {
            		$("#messages").html("<div class='col-12'><img src='/static/img/loading3.gif'/><div>");	
            		},
			success: function(response){ 
			$("#messages").html(response);
			$("#texto").val( "" );	
			},	
		});
	});
	</script>      
      </div>	      
    </div>
  </div>
	<div class="detailpanel">
	      Hola
        </div>
</div>
<!--script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script-->
<script>
$(".messages").animate({ scrollTop: $(document).height() }, "fast");
$("#profile-img").click(function() {
  $("#status-options").toggleClass("active");
});

$(".expand-button").click(function() {
  $("#profile").toggleClass("expanded");
  $("#contacts").toggleClass("expanded");
});

$("#status-options ul li").click(function() {
  $("#profile-img").removeClass();
  $("#status-online").removeClass("active");
  $("#status-away").removeClass("active");
  $("#status-busy").removeClass("active");
  $("#status-offline").removeClass("active");
  $(this).addClass("active");
  
    if($("#status-online").hasClass("active")) {
    $("#profile-img").addClass("online");
  } else if ($("#status-away").hasClass("active")) {
    $("#profile-img").addClass("away");
  } else if ($("#status-busy").hasClass("active")) {
    $("#profile-img").addClass("busy");
  } else if ($("#status-offline").hasClass("active")) {
    $("#profile-img").addClass("offline");
  } else {
    $("#profile-img").removeClass();
  };
    
  $("#status-options").removeClass("active");
});
  
$("#contacts ul li").click(function(){
  $("#contacts ul li").removeClass("active");
  $(this).addClass("active");
});  
   
</script>


{%endblock%}

socialApp/templates/social/messajes.html
<ul>
        {%for message in conversation.message_set.all %}
            	{%if message.direction == 1%}
                	<li class="replies">
            	{%else%}
                	<li class="sent">    
            	{%endif%}
                  	<p><strong>{{message.message_text}}</strong><span  <span class="time_date">{{message.created|date:'d-m-y H:i'}}</span></p>
            	</li>
        {%endfor%}   		
	</ul>     
<script>
    $(".messages").animate({ scrollTop: $(document).height() }, "fast");
</script>
      

socialApp/templates/social/send.html
{% extends "base.html" %}
{%block head_content%}
{% load static %}
<!--link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet"-->
<link href="{% static 'css/emoji.css'%}" rel="stylesheet">
<title>Envio de Whatsapp</title>
{% endblock %}
{% block container %}
  <div class="container-fluid">
   <div class="card mb-4">
     <div class="card-header">Envio de Mensaje</div>
     <div class="card-body">                       
        {%if message is not None %}
          {%if message%}
            <div class="alert alert-success" role="alert">
              <p>El mensaje ha sido enviado correctamente.</p>
            </div> 
          {%else%}
             <div class="alert alert-danger" role="alert">
               <p>El mensaje no ha sido enviado.</p>
             </div>
          {%endif%}   
        {%endif%}    
        <form action="{%url 'send'%}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
          <label>Numero Destino</label>
          <input type="text" name="destino" class="form-control" placeholder="5959XXXXXX"/> 
        </div>
        <div class="form-group">
          <label>Mensaje</label>
            <textarea name="text" class="form-control textarea-control"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
        </form>
      </div>                                              
    </div>
  </div>                                                   
<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
<!-- ** Don't forget to Add jQuery here ** -->
<script src="{% static 'js/config.js' %}"></script>
<script src="{% static 'js/util.js' %}"></script>
<script src="{% static 'js/jquery.emojiarea.js' %}"></script>
<script src="{% static 'js/emoji-picker.js' %}"></script>
<!-- End emoji-picker JavaScript -->
{% endblock %}
                                               
                                               